
package com.atwhere.p2p.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.atwhere.p2p.webservicexmlandsoap.MyXmlService;
import com.atwhere.p2p.webservicexmlandsoap.MyXmlServiceImplService;
import com.atwhere.p2p.webservicexmlandsoap.Student;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-03-15T22:58:21.861+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class MyXmlService_MyXmlServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservicexmlandsoap.p2p.atwhere.com/", "MyXmlServiceImplService");

    private MyXmlService_MyXmlServiceImplPort_Client() {}

    public static void main(String args[]) throws java.lang.Exception {
    	
        URL wsdlURL = MyXmlServiceImplService.WSDL_LOCATION;
        
        //以下注释的代码，可要，可不要
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
      
        MyXmlServiceImplService ss = new MyXmlServiceImplService(wsdlURL, SERVICE_NAME);
        MyXmlService port = ss.getMyXmlServiceImplPort(); 
        
        Student student = port.getStudent(6);
        List<Student> students = port.getStudents("小明", 8);
       
        System.out.println(student);
        System.out.println(students);
       
        
    }

}
